### ISSUE TITLE
Make tabs (on top) autosize to filename width

### ISSUE THREAD

**Issue by DerellLicht** [Alexey-T/SynWrite#34]
This would be handy when I have numerous files open.  
In current implementation, alot of space is wasted on the tabs.

**Comment by Alexey-T** [comment]
I can do this autosize of tabs, but later
If you make donation (not small!) then I can do it inside a week

For ATtabs code and 2 editors: SynWrite, CudaText

**Comment by Alexey-T** [comment]
@kvichans 
@jolinux 
@DerellLicht 
@Andreas123456 
Maybe you interested (for CudaText too)

**Comment by kvichans** [comment]
Very usefull feature

**Comment by Alexey-T** [comment]
@kvichans You can make donation for this?

**Comment by DerellLicht** [comment]
Unfortunately, I got laid off from that contracting job, last month, and am currently unemployed.  So donations are out for the moment.  If/when I get another job, I'll be happy to make a donation, for all the work you've done for SynWrite !

**Comment by jolinux** [comment]
Hello,  if you have many open TABs and it autosize to filename the problem is by short names (like test.txt) the tab-size is very short if you have many tabs (> 20) open. So its a problem to hit the tab with the mouse !?
By no autosize all tabs the same problem to hit.  
Whats the problem to change to this feature ?  Problem to read the filename ?  A window with a Listtool for open tabs !?

**Comment by Alexey-T** [comment]
problem is make OK tabs-control.
i use ATtabs. it needs to make this feature.

**Comment by Alexey-T** [comment]
If none will do donation, I will delay it for future
